language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip websockets cyclus cycamore docker-pycreds sphinx cloud_sptheme numpydoc pytest
  - source activate test-environment
  - python setup.py install
  - pip install docker

script:
    - set -e
    - pytest -v
    - cd docs && make html && cd ..
    - conda install doctr
    - doctr deploy --deploy-repo ergs/rickshaw-docs .

env:
      global:
        - secure: "1qQkq/Fa++W3WwbQE2zYdIEGOjfc4XZqxJ9cNozHtH2wavgSnkLnQNHjeKwtRHb4rXT1gs5N+Bl+itgkFLSkijAyinUOB3rCqy58zto/Ie2IoXpF25XeSzS7VU1uvlvvJgu0goPv88nq8OJ/Hy/qStt/U41LSluuenRPDtqI1hHbTm6vPeyM7v7c4NyuK5SAZpOzikAnugAEa5SLOKbfP7VtTclBxBO9R/6HpmfmjXCJ+6yTjHCLsDpWHyIoMr5UDELfsjl9O2oI7BxkUtK+tKFgVOvBeyavLGa/Ot7CvDQJ8e8058KqLN70A1OvyAjOI6+OBcFODejATH3NwuWeGD3408zHWK2Tr19ptXajUPfLyVnS4YOfTZvMtjZVnkOGP8GfP/fqIBiQZlqHq62jU4KvKR0aFkW++CqKSyXHbs/ydyCJyiXc8umLqeFx70ZkkZnCClo+m5V8UDfpCJ4dewqAPrKnEATpyYyt/vsXgOxd77pW70Jj/OSemDB3OLsgD+fagFA4dW+Zp+NvaTFsl3tDP/VfQ5y9P4TxE2Y6Z01wsOdxz28rzEC6Vqll5dihVNxx/Jyk0YoNHBiIVQkCTa9adDy3YPgFDGvj4C2OS5KRcdE/MIcaguiW36CnqXBx/qChoDrOaCdhoTciwe/Yz4D9+DTJDrNObiztNtcQSQ0="
